### ISSUE TITLE
Problems with URL management

### ISSUE THREAD

**Issue by ilario** [freifunk/projects.freifunk.net-contents#65]
Hi all!
I just realized that if you take the URL for the "OpenWrt device page" project and you open it again, the "LibreMesh LiMe-App architecture homogeneization" projects pops up instead.
Try with this link:
https://projects.freifunk.net/#/projects?project=openwrt_device_page&lang=en

**Comment by andibraeu** [comment]
should work now, can you please check it?

**Comment by ilario** [comment]
Perfect and superfast :D Thanks!
